## Intro to sklearn

##  End-to-end workflow

In [10]:
import pandas as pd
import numpy as np
heart_disease = pd.read_csv("heart-disease.csv")
heart_disease

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal,target
0,63,1,3,145,233,1,0,150,0,2.3,0,0,1,1
1,37,1,2,130,250,0,1,187,0,3.5,0,0,2,1
2,41,0,1,130,204,0,0,172,0,1.4,2,0,2,1
3,56,1,1,120,236,0,1,178,0,0.8,2,0,2,1
4,57,0,0,120,354,0,1,163,1,0.6,2,0,2,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
298,57,0,0,140,241,0,1,123,1,0.2,1,0,3,0
299,45,1,3,110,264,0,1,132,0,1.2,1,0,3,0
300,68,1,0,144,193,1,1,141,0,3.4,1,2,3,0
301,57,1,0,130,131,0,1,115,1,1.2,1,1,3,0
302,57,0,1,130,236,0,0,174,0,0.0,1,1,2,0

In [11]:
#features matrix
X = heart_disease.drop("target",axis=1)

#labels
Y = heart_disease["target"]
X

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal
0,63,1,3,145,233,1,0,150,0,2.3,0,0,1
1,37,1,2,130,250,0,1,187,0,3.5,0,0,2
2,41,0,1,130,204,0,0,172,0,1.4,2,0,2
3,56,1,1,120,236,0,1,178,0,0.8,2,0,2
4,57,0,0,120,354,0,1,163,1,0.6,2,0,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...
298,57,0,0,140,241,0,1,123,1,0.2,1,0,3
299,45,1,3,110,264,0,1,132,0,1.2,1,0,3
300,68,1,0,144,193,1,1,141,0,3.4,1,2,3
301,57,1,0,130,131,0,1,115,1,1.2,1,1,3
302,57,0,1,130,236,0,0,174,0,0.0,1,1,2

In [12]:
#choosing ML model and hyperparameters
from sklearn.ensemble import RandomForestClassifier 
clf = RandomForestClassifier()

#default hyperparameters
clf.get_params()

{'bootstrap': True,
 'ccp_alpha': 0.0,
 'class_weight': None,
 'criterion': 'gini',
 'max_depth': None,
 'max_features': 'auto',
 'max_leaf_nodes': None,
 'max_samples': None,
 'min_impurity_decrease': 0.0,
 'min_impurity_split': None,
 'min_samples_leaf': 1,
 'min_samples_split': 2,
 'min_weight_fraction_leaf': 0.0,
 'n_estimators': 100,
 'n_jobs': None,
 'oob_score': False,
 'random_state': None,
 'verbose': 0,
 'warm_start': False}

In [13]:
#fit model to training data
from sklearn.model_selection import train_test_split

X_train, X_test, Y_train, Y_test = train_test_split(X,Y,test_size=0.2)

In [14]:
clf.fit(X_train,Y_train)

RandomForestClassifier()

In [17]:
#make predictions with test data
Y_preds = clf.predict(X_test)
Y_preds

array([0, 0, 0, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0,
       1, 0, 1, 1, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1,
       0, 0, 0, 0, 1, 1, 1, 0, 0, 1, 1, 0, 1, 0, 0, 1, 0], dtype=int64)

In [21]:
#evaluate the model on training data and test data
clf.score(X_train,Y_train)

1.0

In [22]:
clf.score(X_test,Y_test)

0.7868852459016393

In [26]:
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score

print(classification_report(Y_test,Y_preds))

              precision    recall  f1-score   support

           0       0.74      0.82      0.78        28
           1       0.83      0.76      0.79        33

    accuracy                           0.79        61
   macro avg       0.79      0.79      0.79        61
weighted avg       0.79      0.79      0.79        61

In [27]:
print(confusion_matrix(Y_test,Y_preds))

[[23  5]
 [ 8 25]]

In [28]:
accuracy_score(Y_test,Y_preds)

0.7868852459016393

In [31]:
#improve the model (e.g different n_estimators/number of trees)
for i in range(10,100,10):
    clf = RandomForestClassifier(n_estimators=i).fit(X_train,Y_train)
    print(f'Training size: {i}%')
    print(f'Accuracy: {clf.score(X_test,Y_test)}')
    print()

Training size: 10%
Accuracy: 0.7540983606557377

Training size: 20%
Accuracy: 0.7704918032786885

Training size: 30%
Accuracy: 0.8032786885245902

Training size: 40%
Accuracy: 0.819672131147541

Training size: 50%
Accuracy: 0.8032786885245902

Training size: 60%
Accuracy: 0.819672131147541

Training size: 70%
Accuracy: 0.8032786885245902

Training size: 80%
Accuracy: 0.8032786885245902

Training size: 90%
Accuracy: 0.8032786885245902

In [32]:
#save the model + load it
import pickle

pickle.dump(clf, open("random-forest-model.pkl", "wb"))

In [33]:
loaded_model = pickle.load(open("random-forest-model.pkl", "rb"))
loaded_model.score(X_test,Y_test)

0.8032786885245902